POST  http://localhost:3002/api/persons
Content-Type: application/json

{
    "name": "Carlos Villa",
    "number": "213-12345"
}
###
GET http://localhost:3002/api/persons
###

GET http://localhost:3002/api/persons/3
###

DELETE http://localhost:3002/api/persons/1447960814916.8396
