POST  http://localhost:3001/api/people
Content-Type: application/json

{
    "name": "Mike Smith",
    "number": "0317-123-12"
}
###
GET http://localhost:3001/api/people/
###

GET http://localhost:3001/api/people/6019f0b1c279ef5818f51aab
###

DELETE http://localhost:3001/api/people/6025c65841101719100db0e3
